import { PetListing } from "../types/pet";

// Mock pet listings data
// verificationsCount = number of people the user has helped reunite with their pets
// Users with verificationsCount >= 5 get a "Verified Helper" badge
export const mockPets: PetListing[] = [
  {
    id: "2000294311",
    type: "Lost",
    name: "Eva",
    animalType: "Dog",
    gender: "Female",
    breed: "Golden Retriever",
    color: "Golden",
    age: "3 years",
    dateReported: new Date("2024-11-01"),
    location: {
      address: "123 Oak Street, Portland, OR",
      lat: 45.5152,
      lng: -122.6784,
    },
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=400",
    description: "Friendly golden retriever, answers to Eva. Wearing a blue collar.",
    isFollowed: true,
    postedBy: {
      name: "Sarah Johnson",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
      joinedDate: new Date("2023-05-12"),
      listingsCount: 3,
      verificationsCount: 3,
      activeListings: 2,
      sightingsReported: 5,
      followedPets: 4,
      daysActive: 540,
      badges: [
        {
          id: "first-listing",
          name: "First Step",
          description: "Created your first listing",
          earned: true,
          color: "from-yellow-400 to-orange-400",
          icon: "Star",
        },
        {
          id: "active-30",
          name: "Dedicated Member",
          description: "Active for 30 days",
          earned: true,
          progress: 540,
          requirement: 30,
          color: "from-amber-400 to-yellow-400",
          icon: "Zap",
        },
      ],
    },
  },
  {
    id: "2000294312",
    type: "Lost",
    name: "Whiskers",
    animalType: "Cat",
    gender: "Male",
    breed: "Tabby",
    color: "Orange",
    age: "2 years",
    dateReported: new Date("2024-10-28"),
    location: {
      address: "456 Maple Ave, Portland, OR",
      lat: 45.5231,
      lng: -122.6765,
    },
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400",
    description: "Orange tabby cat with white paws. Very shy.",
    isFollowed: false,
    postedBy: {
      name: "Michael Chen",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      joinedDate: new Date("2024-01-20"),
      listingsCount: 2,
      verificationsCount: 0,
      activeListings: 1,
      sightingsReported: 1,
      followedPets: 2,
      daysActive: 15,
      badges: [
        {
          id: "first-listing",
          name: "First Step",
          description: "Created your first listing",
          earned: true,
          color: "from-yellow-400 to-orange-400",
          icon: "Star",
        },
      ],
    },
  },
  {
    id: "2000294313",
    type: "Sighting",
    name: "Unknown",
    animalType: "Dog",
    gender: "Unknown",
    color: "Black and White",
    dateReported: new Date("2024-11-06"),
    location: {
      address: "789 Pine Road, Portland, OR",
      lat: 45.5289,
      lng: -122.6745,
    },
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
    description: "Spotted near the park, looks lost and scared.",
    isFollowed: false,
    postedBy: {
      name: "Emily Rodriguez",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
      joinedDate: new Date("2023-08-15"),
      listingsCount: 4,
      verificationsCount: 7,
      activeListings: 2,
      sightingsReported: 12,
      followedPets: 8,
      daysActive: 450,
      badges: [
        {
          id: "first-listing",
          name: "First Step",
          description: "Created your first listing",
          earned: true,
          color: "from-yellow-400 to-orange-400",
          icon: "Star",
        },
        {
          id: "helper-5",
          name: "Community Helper",
          description: "Helped 5 people find their pets",
          earned: true,
          color: "from-pink-400 to-rose-400",
          icon: "Heart",
        },
        {
          id: "sighter-10",
          name: "Neighborhood Watch",
          description: "Reported 10 sightings",
          earned: true,
          color: "from-green-400 to-emerald-400",
          icon: "MapPin",
        },
      ],
    },
  },
  {
    id: "2000294314",
    type: "Lost",
    name: "Fluffy",
    animalType: "Bunny",
    gender: "Female",
    breed: "Holland Lop",
    color: "White",
    age: "1 year",
    dateReported: new Date("2024-09-15"),
    location: {
      address: "321 Birch Lane, Portland, OR",
      lat: 45.5198,
      lng: -122.6820,
    },
    status: "Stale",
    imageUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=400",
    description: "Small white bunny with floppy ears.",
    isFollowed: false,
    postedBy: {
      name: "David Kim",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
      joinedDate: new Date("2024-03-10"),
      listingsCount: 2,
      verificationsCount: 1,
      activeListings: 1,
      sightingsReported: 3,
      followedPets: 5,
      daysActive: 240,
      badges: [
        {
          id: "first-listing",
          name: "First Step",
          description: "Created your first listing",
          earned: true,
          color: "from-yellow-400 to-orange-400",
          icon: "Star",
        },
      ],
    },
  },
  {
    id: "2000294315",
    type: "Lost",
    name: "Charlie",
    animalType: "Bird",
    gender: "Male",
    breed: "Cockatiel",
    color: "Gray and Yellow",
    age: "4 years",
    dateReported: new Date("2024-11-05"),
    location: {
      address: "654 Cedar St, Portland, OR",
      lat: 45.5167,
      lng: -122.6801,
    },
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400",
    description: "Gray cockatiel with yellow face. Whistles melodies.",
    isFollowed: true,
    postedBy: {
      name: "Jennifer Martinez",
      avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100",
      joinedDate: new Date("2022-11-03"),
      listingsCount: 8,
      verificationsCount: 12,
      activeListings: 3,
      sightingsReported: 20,
      followedPets: 15,
      daysActive: 735,
      badges: [
        {
          id: "first-listing",
          name: "First Step",
          description: "Created your first listing",
          earned: true,
          color: "from-yellow-400 to-orange-400",
          icon: "Star",
        },
        {
          id: "helper-5",
          name: "Community Helper",
          description: "Helped 5 people find their pets",
          earned: true,
          color: "from-pink-400 to-rose-400",
          icon: "Heart",
        },
        {
          id: "helper-10",
          name: "Guardian Angel",
          description: "Helped 10 people find their pets",
          earned: true,
          progress: 12,
          requirement: 10,
          color: "from-purple-400 to-indigo-400",
          icon: "Trophy",
        },
        {
          id: "sighter-10",
          name: "Neighborhood Watch",
          description: "Reported 10 sightings",
          earned: true,
          color: "from-green-400 to-emerald-400",
          icon: "MapPin",
        },
        {
          id: "active-30",
          name: "Dedicated Member",
          description: "Active for 30 days",
          earned: true,
          progress: 735,
          requirement: 30,
          color: "from-amber-400 to-yellow-400",
          icon: "Zap",
        },
        {
          id: "follower-10",
          name: "Pet Advocate",
          description: "Following 10 pets",
          earned: true,
          progress: 15,
          requirement: 10,
          color: "from-teal-400 to-cyan-400",
          icon: "Users",
        },
      ],
    },
  },
  {
    id: "2000294316",
    type: "Lost",
    name: "Mittens",
    animalType: "Cat",
    gender: "Female",
    breed: "Siamese",
    color: "Cream and Brown",
    age: "5 years",
    dateReported: new Date("2024-10-20"),
    location: {
      address: "987 Elm Drive, Portland, OR",
      lat: 45.5210,
      lng: -122.6789,
    },
    status: "Found",
    imageUrl: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=400",
    description: "Siamese cat with blue eyes. Very vocal.",
    isFollowed: false,
    postedBy: {
      name: "Alex Thompson",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
      joinedDate: new Date("2023-02-28"),
      listingsCount: 3,
      verificationsCount: 5,
      activeListings: 1,
      sightingsReported: 6,
      followedPets: 7,
      daysActive: 615,
      badges: [
        {
          id: "first-listing",
          name: "First Step",
          description: "Created your first listing",
          earned: true,
          color: "from-yellow-400 to-orange-400",
          icon: "Star",
        },
        {
          id: "helper-5",
          name: "Community Helper",
          description: "Helped 5 people find their pets",
          earned: true,
          color: "from-pink-400 to-rose-400",
          icon: "Heart",
        },
        {
          id: "sighter-5",
          name: "Eagle Eye",
          description: "Reported 5 sightings",
          earned: true,
          color: "from-blue-400 to-cyan-400",
          icon: "MapPin",
        },
        {
          id: "active-30",
          name: "Dedicated Member",
          description: "Active for 30 days",
          earned: true,
          progress: 615,
          requirement: 30,
          color: "from-amber-400 to-yellow-400",
          icon: "Zap",
        },
      ],
    },
  },
];
